name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python and Pip
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip

  run-tests:
    runs-on: ubuntu-latest
    needs: setup-environment
    if: github.event.pull_request.merged == false || github.event.pull_request.merged == true
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up SSH Key for GitHub
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SECRET_NAME }}

      - name: Run Tests
        run: |
          pwd
          echo "Running tests on the pull request"
          git clone git@github.com:virasemi/uec-compliance.git       
          cd uec-compliance
          git checkout feature-schema-tool
          pwd
          pip3 install -r requirements.txt
          python3 schema-tool/schema-tool.py --infile ../checklists/phy-ll/PHY-LL_Matrix_and_Checklist_v0.1.xlsx

  merge-actions:
    runs-on: self-hosted
    if: github.event.pull_request.merged == true
    steps:
      - name: Perform Post-Merge Actions
        run: |
          echo "Executing post-merge"
