name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  run-tests:
    runs-on: self-hosted
    if: github.event.pull_request.merged == false || github.event.pull_request.merged == true
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          echo "Running tests on the pull request"
          git clone git@github.com:virasemi/uec-compliance.git        
          cd uec-compliance
          git checkout feature-schema-tool
          python3 schema-tool/schema-tool.py --infile ../../checklists/phy-ll/PHY-LL_Matrix_and_Checklist_v0.1.xlsx


  merge-actions:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Perform Post-Merge Actions
        run: |
          echo "Executing post-merge"
