name: bridge tap workflow

on:
  workflow_dispatch:  # This replaces the pull_request trigger with a manual trigger

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Install bridge-utils
        run: |
          sudo apt update
          sudo apt install -y iproute2 bridge-utils

      - name: Create TAP Interfaces
        run: |
          sudo ip tuntap add dev tap0 mode tap user $USER
          sudo ip tuntap add dev tap1 mode tap user $USER
          sudo ip link set tap0 up
          sudo ip link set tap1 up

      - name: Create the Bridge
        run: |
          sudo ip link add name br0 type bridge
          sudo ip link set tap0 master br0
          sudo ip link set tap1 master br0

      - name: Bring the Bridge Up
        run: |
          sudo ip link set br0 up
          sudo ip addr add 192.168.100.1/24 dev br0
          sudo ip addr add 192.168.100.10/24 dev tap0
          sudo ip addr add 192.168.100.11/24 dev tap1
          bridge link
          brctl show

  run_tests:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: check tap
        run: |
          pwd
          brctl show
          ping -I tap0 192.168.100.11          
