name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false || github.event.pull_request.merged == true
    steps:
      - name: Install Python and Pip
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip

  run-tests:
    runs-on: ubuntu-latest
    needs: setup-environment
    if: github.event.pull_request.merged == false || github.event.pull_request.merged == true
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up SSH Key for GitHub
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.TEST_CHECKLIST_SECRET }}

      - name: Git Clone
        run: |
          pwd
          git clone git@github.com:virasemi/uec-compliance.git       
          cd uec-compliance
          git checkout feature-schema-tool
          pip3 install -r requirements.txt

      - name: infile option check
        run: |
          pwd
          python3 schema-tool/schema-tool.py --infile ../checklists/phy-ll/PHY-LL_Matrix_and_Checklist_v0.1.xlsx

      - name: checklist option check
        run: |
          pwd
          python3 schema-tool/schema-tool.py --checklist checklists/phy-ll/PHY-LL_Matrix_and_Checklist_v0.1_checklist.csv

